export const CuisineTypes = {
  american: "american",
  asian: "asian",
  british: "british",
  caribbean: "caribbean",
  centralEurope: "central europe",
  chinese: "chinese",
  easternEurope: "eastern europe",
  french: "french",
  greek: "greek",
  indian: "indian",
  italian: "italian",
  japanese: "japanese",
  korean: "korean",
  kosher: "kosher",
  mediterranean: "mediterranean",
  mexican: "mexican",
  middleEastern: "middle eastern",
  nordic: "nordic",
  southAmerican: "south american",
  southEastAsian: "south east asian",
  world: "world",
}